// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejxcvjaneqdsxwelxwya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqeGN2amFuZXFkc3h3ZWx4d3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4MzMwODksImV4cCI6MjA0OTQwOTA4OX0.5fKGK1DsQIkJmEjaJgQoBdhF2ZRgIN3ByVFoUWeHLYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);